### ISSUE TITLE
Fixing crowdin integration 

### ISSUE THREAD

**Issue by BatoolMM** [kozo2/bioc-talks-and-transcripts#7]
To fix the issue in PR #3 - I made a new fork and a new integration with GitHub in Crowdin. It seems to work fine. @kozo2 You can see my fork in https://github.com/BatoolMM/bioc-talks-and-transcripts where a new PR is open automatically to sync the new translation. 

I'm not sure how you set up the integration in Crowdin (beacuse I can't see it, only you can see it) but we can try two things: 
1- Make sure everything is set up as follow and click in sync, wait a few minutes to see if a new PR is open automatically  
<img width="891" alt="Screen Shot 2021-12-09 at 3 24 14 PM" src="https://user-images.githubusercontent.com/53487593/145470284-f2a2921a-2b9c-4cfc-81b4-a147995d3734.png">

2- If still didn't work, maybe you can give me access to the repo and I can set up a new integration with your repo, if needed - Hopefully, you won't need that!

**Comment by kozo2** [comment]
@BatoolMM I think https://github.com/BatoolMM/bioc-talks-and-transcripts/pull/1/files does not have the translated files (== ja/japanese_transcripts/Lori_biocasia2021.srt)
![image](https://user-images.githubusercontent.com/12192/145479979-34ec6414-4f04-477c-ad02-c0e1995ddcce.png)
I think it's only the original source files (== English srt) that has your PR.
![image](https://user-images.githubusercontent.com/12192/145481276-eb0f5a62-4631-4cc4-9562-d6316d3ee260.png)

What do you think about this?

**Comment by kozo2** [comment]
1. These are screenshots of my GitHub integration
![image](https://user-images.githubusercontent.com/12192/145480473-0b64ec32-3fac-4bb7-89e5-6562bb6f6c75.png)
![image](https://user-images.githubusercontent.com/12192/145480497-0b69ae30-fc9a-424a-a35b-0d4725bb1dc6.png)

**Comment by kozo2** [comment]
2. I invited you to https://github.com/kozo2/bioc-talks-and-transcripts
![image](https://user-images.githubusercontent.com/12192/145480748-e4427a8c-559c-484f-b679-7487709bfe7f.png)

**Comment by BatoolMM** [comment]
Fixed in PR #8.
